#include "common.h"
#include "stdinx.h"
#include "graphics_ctrl.h"
#include "graphics_obj.h"
#include "layer/layer.h"
#include "font/font_style.h"
#include "image.h"
#include "img/img.h"
#include "timer.h"
#include "touch_check.h"

static void L_DETAIL00_start(void);
static void L_DETAIL00_end(void);
static void L_DETAIL00_always(void);

/*
 * タッチ用関数のプロトタイプ宣言があるオブジェクトがタッチの動作が作られていると認識します。
 * 下記の「touch_prototype」部分で囲まれている宣言部をプロトタイプ宣言として認識します。
 * オブジェクトの関数作成して編集を押すと自動で生成されます。
 */
/**********touch_prototype(start)**********/
static void OBJ_IMG_SELECT00_touch(int obj_id , int touch_type);
static void OBJ_IMG_SELECT01_touch(int obj_id , int touch_type);
static void OBJ_IMG_SELECT02_touch(int obj_id , int touch_type);
static void OBJ_IMG_AMSELECT00_touch(int obj_id , int touch_type);
static void OBJ_IMG_NOTICESELECT00_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS00_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS01_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS02_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS03_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS04_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS05_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS06_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS07_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS08_touch(int obj_id , int touch_type);
static void OBJ_RECT_PROCESS09_touch(int obj_id , int touch_type);
/**********touch_prototype(end)**********/


/**********auto(start)**********/
#define OBJ_RECT_SELECT00  1854
#define OBJ_IMG_SELECT00  1684
#define OBJ_IMG_SELECT01  1685
#define OBJ_IMG_SELECT02  1686
#define OBJ_TEXT_SELECT00  1855
#define OBJ_TEXT_SELECT01  1856
#define OBJ_TEXT_SELECT02  1857
#define OBJ_RECT_TITLE00  1683
#define OBJ_TEXT_TITLE00  1851
#define OBJ_TEXT_TITLE01  1852
#define OBJ_TEXT_TITLE02  1853
#define OBJ_IMG_PROCESS_SELECT00  1687
#define OBJ_IMG_AMSELECT00  1688
#define OBJ_IMG_NOTICE00  1689
#define OBJ_IMG_NOTICESELECT00  1690
#define OBJ_RECT_BREAK00  1691
#define OBJ_RECT_BREAK01  1693
#define OBJ_IMG_TABLETITLE00  1692
#define OBJ_IMG_TABLETITLE01  1705
#define OBJ_IMG_TABLETITLE02  1706
#define OBJ_IMG_TABLETITLE03  1707
#define OBJ_IMG_TABLETITLE04  1708
#define OBJ_RECT_TABLE00  1694
#define OBJ_RECT_PROCESS00  1695
#define OBJ_RECT_PROCESS01  1696
#define OBJ_RECT_PROCESS02  1697
#define OBJ_RECT_PROCESS03  1698
#define OBJ_RECT_PROCESS04  1699
#define OBJ_RECT_PROCESS05  1700
#define OBJ_RECT_PROCESS06  1701
#define OBJ_RECT_PROCESS07  1702
#define OBJ_RECT_PROCESS08  1703
#define OBJ_RECT_PROCESS09  1704
#define OBJ_TEXT_PROCESS00  1709
#define OBJ_TEXT_PROCESS01  1710
#define OBJ_TEXT_PROCESS02  1711
#define OBJ_TEXT_PROCESS03  1712
#define OBJ_TEXT_PROCESS04  1713
#define OBJ_TEXT_PROCESS05  1714
#define OBJ_TEXT_PROCESS06  1715
#define OBJ_TEXT_PROCESS07  1716
#define OBJ_TEXT_PROCESS08  1717
#define OBJ_TEXT_PROCESS09  1718
#define OBJ_IMG_UHM00  1719
#define OBJ_IMG_LHM00  1720
#define OBJ_IMG_UHM01  1721
#define OBJ_IMG_LHM01  1722
#define OBJ_IMG_UHM02  1723
#define OBJ_IMG_LHM02  1724
#define OBJ_IMG_UHM03  1725
#define OBJ_IMG_LHM03  1726
#define OBJ_IMG_UHM04  1727
#define OBJ_IMG_LHM04  1728
#define OBJ_IMG_UHM05  1729
#define OBJ_IMG_LHM05  1730
#define OBJ_IMG_UHM06  1731
#define OBJ_IMG_LHM06  1732
#define OBJ_IMG_UHM07  1733
#define OBJ_IMG_LHM07  1734
#define OBJ_IMG_UHM08  1735
#define OBJ_IMG_LHM08  1736
#define OBJ_IMG_UHM09  1737
#define OBJ_IMG_LHM09  1738
#define OBJ_IMG_T_CT01  1740
#define OBJ_IMG_T_CT02  1741
#define OBJ_IMG_T_CT03  1742
#define OBJ_IMG_T_CT04  1743
#define OBJ_IMG_T_CT05  1744
#define OBJ_IMG_T_CT06  1745
#define OBJ_IMG_T_CT07  1746
#define OBJ_IMG_T_CT08  1747
#define OBJ_IMG_T_CT09  1748
#define OBJ_TEXT_T_CT00  1739
#define OBJ_TEXT_TIME011  1749
#define OBJ_TEXT_TIME021  1761
#define OBJ_TEXT_TIME031  1762
#define OBJ_TEXT_TIME041  1763
#define OBJ_TEXT_TIME051  1764
#define OBJ_TEXT_TIME061  1765
#define OBJ_TEXT_TIME071  1766
#define OBJ_TEXT_TIME081  1767
#define OBJ_TEXT_TIME091  1768
#define OBJ_TEXT_TIME012  1750
#define OBJ_TEXT_TIME022  1769
#define OBJ_TEXT_TIME032  1770
#define OBJ_TEXT_TIME042  1771
#define OBJ_TEXT_TIME052  1772
#define OBJ_TEXT_TIME062  1773
#define OBJ_TEXT_TIME072  1774
#define OBJ_TEXT_TIME082  1775
#define OBJ_TEXT_TIME092  1776
#define OBJ_TEXT_TIME013  1751
#define OBJ_TEXT_TIME023  1777
#define OBJ_TEXT_TIME033  1778
#define OBJ_TEXT_TIME043  1779
#define OBJ_TEXT_TIME053  1780
#define OBJ_TEXT_TIME063  1781
#define OBJ_TEXT_TIME073  1782
#define OBJ_TEXT_TIME083  1783
#define OBJ_TEXT_TIME093  1784
#define OBJ_TEXT_TIME014  1752
#define OBJ_TEXT_TIME024  1785
#define OBJ_TEXT_TIME034  1786
#define OBJ_TEXT_TIME044  1787
#define OBJ_TEXT_TIME054  1788
#define OBJ_TEXT_TIME064  1789
#define OBJ_TEXT_TIME074  1790
#define OBJ_TEXT_TIME084  1791
#define OBJ_TEXT_TIME094  1792
#define OBJ_TEXT_CT01  1793
#define OBJ_TEXT_CT02  1794
#define OBJ_TEXT_CT03  1795
#define OBJ_TEXT_CT04  1796
#define OBJ_TEXT_CT05  1797
#define OBJ_TEXT_CT06  1798
#define OBJ_TEXT_CT07  1799
#define OBJ_TEXT_CT08  1800
#define OBJ_TEXT_CT09  1801
#define OBJ_TEXT_UHT00  1802
#define OBJ_TEXT_UHT01  1804
#define OBJ_TEXT_UHT02  1805
#define OBJ_TEXT_UHT03  1806
#define OBJ_TEXT_UHT04  1807
#define OBJ_TEXT_UHT05  1808
#define OBJ_TEXT_UHT06  1809
#define OBJ_TEXT_UHT07  1810
#define OBJ_TEXT_UHT08  1811
#define OBJ_TEXT_UHT09  1812
#define OBJ_TEXT_LHT00  1803
#define OBJ_TEXT_LHT01  1813
#define OBJ_TEXT_LHT02  1814
#define OBJ_TEXT_LHT03  1815
#define OBJ_TEXT_LHT04  1816
#define OBJ_TEXT_LHT05  1817
#define OBJ_TEXT_LHT06  1818
#define OBJ_TEXT_LHT07  1819
#define OBJ_TEXT_LHT08  1820
#define OBJ_TEXT_LHT09  1821
#define OBJ_TEXT_DAMPER00  1822
#define OBJ_TEXT_DAMPER01  1823
#define OBJ_TEXT_DAMPER02  1824
#define OBJ_TEXT_DAMPER03  1825
#define OBJ_TEXT_DAMPER04  1826
#define OBJ_TEXT_DAMPER05  1827
#define OBJ_TEXT_DAMPER06  1828
#define OBJ_TEXT_DAMPER07  1829
#define OBJ_TEXT_DAMPER08  1830
#define OBJ_TEXT_DAMPER09  1831
#define OBJ_IMG_DAMPER00  1858
#define OBJ_IMG_DAMPER01  1866
#define OBJ_IMG_DAMPER02  1867
#define OBJ_IMG_DAMPER03  1868
#define OBJ_IMG_DAMPER04  1869
#define OBJ_IMG_DAMPER05  1870
#define OBJ_IMG_DAMPER06  1871
#define OBJ_IMG_DAMPER07  1872
#define OBJ_IMG_DAMPER08  1873
#define OBJ_IMG_DAMPER09  1874
#define OBJ_TEXT_STEAM00  1832
#define OBJ_TEXT_STEAM01  1833
#define OBJ_TEXT_STEAM02  1834
#define OBJ_TEXT_STEAM03  1835
#define OBJ_TEXT_STEAM04  1836
#define OBJ_TEXT_STEAM05  1837
#define OBJ_TEXT_STEAM06  1838
#define OBJ_TEXT_STEAM07  1839
#define OBJ_TEXT_STEAM08  1840
#define OBJ_TEXT_STEAM09  1841
#define OBJ_IMG_STEAM01  1842
#define OBJ_IMG_STEAM02  1843
#define OBJ_IMG_STEAM03  1844
#define OBJ_IMG_STEAM04  1845
#define OBJ_IMG_STEAM05  1846
#define OBJ_IMG_STEAM06  1847
#define OBJ_IMG_STEAM07  1848
#define OBJ_IMG_STEAM08  1849
#define OBJ_IMG_STEAM09  1850
#define OBJ_RECT_TABLE01  1705
#define OBJ_RECT_TABLE02  1706
#define OBJ_RECT_TABLE03  1707
#define OBJ_RECT_TABLE04  1708

extern const wchar_t TEXT_DATA_NON;
static const wchar_t OBJ_TEXT_SELECT00_TEXT[] = L"工程削除";
static const wchar_t OBJ_TEXT_SELECT01_TEXT[] = L"工程編集";
static const wchar_t OBJ_TEXT_SELECT02_TEXT[] = L"リストへ";
static const wchar_t OBJ_TEXT_TITLE00_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TITLE01_TEXT[] = L"：";
static const wchar_t OBJ_TEXT_TITLE02_TEXT[] = L"××××××××××";
static const wchar_t OBJ_TEXT_PROCESS00_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_PROCESS01_TEXT[] = L"1";
static const wchar_t OBJ_TEXT_PROCESS02_TEXT[] = L"2";
static const wchar_t OBJ_TEXT_PROCESS03_TEXT[] = L"3";
static const wchar_t OBJ_TEXT_PROCESS04_TEXT[] = L"4";
static const wchar_t OBJ_TEXT_PROCESS05_TEXT[] = L"5";
static const wchar_t OBJ_TEXT_PROCESS06_TEXT[] = L"6";
static const wchar_t OBJ_TEXT_PROCESS07_TEXT[] = L"7";
static const wchar_t OBJ_TEXT_PROCESS08_TEXT[] = L"8";
static const wchar_t OBJ_TEXT_PROCESS09_TEXT[] = L"9";
static const wchar_t OBJ_TEXT_T_CT00_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_TIME011_TEXT[] = L"15";
static const wchar_t OBJ_TEXT_TIME021_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME031_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME041_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME051_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME061_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME071_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME081_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME091_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME012_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME022_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME032_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME042_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME052_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME062_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME072_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME082_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME092_TEXT[] = L"\'";
static const wchar_t OBJ_TEXT_TIME013_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME023_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME033_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME043_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME053_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME063_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME073_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME083_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME093_TEXT[] = L"00";
static const wchar_t OBJ_TEXT_TIME014_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME024_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME034_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME044_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME054_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME064_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME074_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME084_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_TIME094_TEXT[] = L"\"";
static const wchar_t OBJ_TEXT_CT01_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT02_TEXT[] = L"80";
static const wchar_t OBJ_TEXT_CT03_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT04_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT05_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT06_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT07_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT08_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_CT09_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT00_TEXT[] = L"150";
static const wchar_t OBJ_TEXT_UHT01_TEXT[] = L"150";
static const wchar_t OBJ_TEXT_UHT02_TEXT[] = L"100";
static const wchar_t OBJ_TEXT_UHT03_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT04_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT05_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT06_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT07_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT08_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_UHT09_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT00_TEXT[] = L"150";
static const wchar_t OBJ_TEXT_LHT01_TEXT[] = L"150";
static const wchar_t OBJ_TEXT_LHT02_TEXT[] = L"100";
static const wchar_t OBJ_TEXT_LHT03_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT04_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT05_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT06_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT07_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT08_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_LHT09_TEXT[] = L"0";
static const wchar_t OBJ_TEXT_DAMPER00_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER01_TEXT[] = L"自然";
static const wchar_t OBJ_TEXT_DAMPER02_TEXT[] = L"強制";
static const wchar_t OBJ_TEXT_DAMPER03_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER04_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER05_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER06_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER07_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER08_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_DAMPER09_TEXT[] = L"閉";
static const wchar_t OBJ_TEXT_STEAM00_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM01_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM02_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM03_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM04_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM05_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM06_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM07_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM08_TEXT[] = L"－";
static const wchar_t OBJ_TEXT_STEAM09_TEXT[] = L"－";

static const obj_data_t object_list[181] = {
	{OBJ_RECT_SELECT00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,421,13,2,150,ON,OFF,0xFFFFFFFF,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_SELECT00,cd_deleate_a_off,cd_deleate_a_on,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,30,13,117,137,ON,ON,0,0,(wchar_t *)&TEXT_DATA_NON,OBJ_IMG_SELECT00_touch},
	{OBJ_IMG_SELECT01,cd_edit_a_off,cd_edit_a_on,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,280,13,117,137,ON,ON,0,0,(wchar_t *)&TEXT_DATA_NON,OBJ_IMG_SELECT01_touch},
	{OBJ_IMG_SELECT02,cd_listback_a_off,cd_listback_a_on,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,446,13,117,137,ON,ON,0,0,(wchar_t *)&TEXT_DATA_NON,OBJ_IMG_SELECT02_touch},
	{OBJ_TEXT_SELECT00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,89,140,200,24,ON,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_SELECT00_TEXT,NULL},
	{OBJ_TEXT_SELECT01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,339,140,200,24,ON,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_SELECT01_TEXT,NULL},
	{OBJ_TEXT_SELECT02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,505,140,200,24,ON,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_SELECT02_TEXT,NULL},
	{OBJ_RECT_TITLE00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,0,175,600,55,ON,OFF,0xFF007A44,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_TEXT_TITLE00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,70,202,200,24,ON,OFF,0,Font32,(wchar_t *)&OBJ_TEXT_TITLE00_TEXT,NULL},
	{OBJ_TEXT_TITLE01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,115,202,200,24,ON,OFF,0,Font32,(wchar_t *)&OBJ_TEXT_TITLE01_TEXT,NULL},
	{OBJ_TEXT_TITLE02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_LEFT,135,202,200,24,ON,OFF,0,Font32,(wchar_t *)&OBJ_TEXT_TITLE02_TEXT,NULL},
	{OBJ_IMG_PROCESS_SELECT00,logo_process_select,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,20,238,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_AMSELECT00,amselect_a_off,amselect_a_on,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,130,240,117,137,ON,ON,0,0,(wchar_t *)&TEXT_DATA_NON,OBJ_IMG_AMSELECT00_touch},
	{OBJ_IMG_NOTICE00,logo_notice,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,315,240,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_NOTICESELECT00,noticeselect_b_off,noticeselect_b_on,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,430,240,117,137,ON,ON,0,0,(wchar_t *)&TEXT_DATA_NON,OBJ_IMG_NOTICESELECT00_touch},
	{OBJ_RECT_BREAK00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,299,245,2,100,ON,OFF,0xFFFFFFFF,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_BREAK01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,10,358,580,2,ON,OFF,0xFFFFFFFF,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_TABLETITLE00,logo_tabletitle1,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,45,360,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_TABLETITLE01,logo_tabletitle2,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,153,360,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_TABLETITLE02,logo_tabletitle3,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,263,360,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_TABLETITLE03,logo_tabletitle4,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,360,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_TABLETITLE04,logo_tabletitle5,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,480,360,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_TABLE00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,47,427,538,573,ON,OFF,0xFF5a5a5a,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_PROCESS00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,430,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS00_touch},
	{OBJ_RECT_PROCESS01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,487,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS01_touch},
	{OBJ_RECT_PROCESS02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,544,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS02_touch},
	{OBJ_RECT_PROCESS03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,601,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS03_touch},
	{OBJ_RECT_PROCESS04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,658,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS04_touch},
	{OBJ_RECT_PROCESS05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,715,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS05_touch},
	{OBJ_RECT_PROCESS06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,772,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS06_touch},
	{OBJ_RECT_PROCESS07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,829,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS07_touch},
	{OBJ_RECT_PROCESS08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,886,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS08_touch},
	{OBJ_RECT_PROCESS09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,50,943,532,54,ON,ON,0xFF000000,0,(wchar_t *)&TEXT_DATA_NON,OBJ_RECT_PROCESS09_touch},
	{OBJ_TEXT_PROCESS00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,455,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS00_TEXT,NULL},
	{OBJ_TEXT_PROCESS01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,512,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS01_TEXT,NULL},
	{OBJ_TEXT_PROCESS02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,569,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS02_TEXT,NULL},
	{OBJ_TEXT_PROCESS03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,626,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS03_TEXT,NULL},
	{OBJ_TEXT_PROCESS04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,683,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS04_TEXT,NULL},
	{OBJ_TEXT_PROCESS05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,740,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS05_TEXT,NULL},
	{OBJ_TEXT_PROCESS06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,797,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS06_TEXT,NULL},
	{OBJ_TEXT_PROCESS07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,854,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS07_TEXT,NULL},
	{OBJ_TEXT_PROCESS08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,911,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS08_TEXT,NULL},
	{OBJ_TEXT_PROCESS09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,25,968,200,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_PROCESS09_TEXT,NULL},
	{OBJ_IMG_UHM00,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,430,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM00,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,430,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM01,logo_mode_medium,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,487,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM01,logo_mode_medium,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,487,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM02,logo_mode_low,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,544,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM02,logo_mode_low,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,544,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM03,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,601,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM03,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,601,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM04,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,658,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM04,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,658,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM05,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,715,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM05,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,715,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM06,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,772,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM06,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,772,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM07,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,829,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM07,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,829,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM08,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,886,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM08,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,886,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_UHM09,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,162,943,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_LHM09,logo_mode_high,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,269,943,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT01,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,487,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT02,logo_mode_coretemp,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,544,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT03,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,601,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT04,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,658,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT05,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,715,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT06,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,772,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT07,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,829,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT08,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,886,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_T_CT09,logo_mode_time,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,53,943,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_TEXT_T_CT00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,102,457,104,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_T_CT00_TEXT,NULL},
	{OBJ_TEXT_TIME011,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_LEFT,100,514,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_TIME011_TEXT,NULL},
	{OBJ_TEXT_TIME021,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,128,571,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME021_TEXT,NULL},
	{OBJ_TEXT_TIME031,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,628,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME031_TEXT,NULL},
	{OBJ_TEXT_TIME041,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,685,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME041_TEXT,NULL},
	{OBJ_TEXT_TIME051,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,742,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME051_TEXT,NULL},
	{OBJ_TEXT_TIME061,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,799,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME061_TEXT,NULL},
	{OBJ_TEXT_TIME071,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,856,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME071_TEXT,NULL},
	{OBJ_TEXT_TIME081,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,913,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME081_TEXT,NULL},
	{OBJ_TEXT_TIME091,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,118,970,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME091_TEXT,NULL},
	{OBJ_TEXT_TIME012,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_LEFT,120,514,104,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_TIME012_TEXT,NULL},
	{OBJ_TEXT_TIME022,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,569,104,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_TIME022_TEXT,NULL},
	{OBJ_TEXT_TIME032,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,626,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME032_TEXT,NULL},
	{OBJ_TEXT_TIME042,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,683,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME042_TEXT,NULL},
	{OBJ_TEXT_TIME052,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,740,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME052_TEXT,NULL},
	{OBJ_TEXT_TIME062,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,797,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME062_TEXT,NULL},
	{OBJ_TEXT_TIME072,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,854,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME072_TEXT,NULL},
	{OBJ_TEXT_TIME082,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,911,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME082_TEXT,NULL},
	{OBJ_TEXT_TIME092,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,124,968,104,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME092_TEXT,NULL},
	{OBJ_TEXT_TIME013,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,514,110,16,ON,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME013_TEXT,NULL},
	{OBJ_TEXT_TIME023,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,571,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME023_TEXT,NULL},
	{OBJ_TEXT_TIME033,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,628,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME033_TEXT,NULL},
	{OBJ_TEXT_TIME043,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,685,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME043_TEXT,NULL},
	{OBJ_TEXT_TIME053,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,742,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME053_TEXT,NULL},
	{OBJ_TEXT_TIME063,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,799,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME063_TEXT,NULL},
	{OBJ_TEXT_TIME073,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,856,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME073_TEXT,NULL},
	{OBJ_TEXT_TIME083,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,913,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME083_TEXT,NULL},
	{OBJ_TEXT_TIME093,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,144,970,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME093_TEXT,NULL},
	{OBJ_TEXT_TIME014,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,512,110,16,ON,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME014_TEXT,NULL},
	{OBJ_TEXT_TIME024,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,569,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME024_TEXT,NULL},
	{OBJ_TEXT_TIME034,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,626,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME034_TEXT,NULL},
	{OBJ_TEXT_TIME044,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,683,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME044_TEXT,NULL},
	{OBJ_TEXT_TIME054,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,740,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME054_TEXT,NULL},
	{OBJ_TEXT_TIME064,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,797,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME064_TEXT,NULL},
	{OBJ_TEXT_TIME074,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,854,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME074_TEXT,NULL},
	{OBJ_TEXT_TIME084,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,911,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME084_TEXT,NULL},
	{OBJ_TEXT_TIME094,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_RIGHT,150,968,110,16,OFF,OFF,0,Font16,(wchar_t *)&OBJ_TEXT_TIME094_TEXT,NULL},
	{OBJ_TEXT_CT01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,514,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT01_TEXT,NULL},
	{OBJ_TEXT_CT02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,571,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT02_TEXT,NULL},
	{OBJ_TEXT_CT03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,628,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT03_TEXT,NULL},
	{OBJ_TEXT_CT04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,685,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT04_TEXT,NULL},
	{OBJ_TEXT_CT05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,742,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT05_TEXT,NULL},
	{OBJ_TEXT_CT06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,799,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT06_TEXT,NULL},
	{OBJ_TEXT_CT07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,856,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT07_TEXT,NULL},
	{OBJ_TEXT_CT08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,913,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT08_TEXT,NULL},
	{OBJ_TEXT_CT09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,124,970,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_CT09_TEXT,NULL},
	{OBJ_TEXT_UHT00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,457,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT00_TEXT,NULL},
	{OBJ_TEXT_UHT01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,514,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT01_TEXT,NULL},
	{OBJ_TEXT_UHT02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,571,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT02_TEXT,NULL},
	{OBJ_TEXT_UHT03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,628,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT03_TEXT,NULL},
	{OBJ_TEXT_UHT04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,685,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT04_TEXT,NULL},
	{OBJ_TEXT_UHT05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,742,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT05_TEXT,NULL},
	{OBJ_TEXT_UHT06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,799,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT06_TEXT,NULL},
	{OBJ_TEXT_UHT07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,856,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT07_TEXT,NULL},
	{OBJ_TEXT_UHT08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,913,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT08_TEXT,NULL},
	{OBJ_TEXT_UHT09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,226,970,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_UHT09_TEXT,NULL},
	{OBJ_TEXT_LHT00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,457,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT00_TEXT,NULL},
	{OBJ_TEXT_LHT01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,514,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT01_TEXT,NULL},
	{OBJ_TEXT_LHT02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,571,110,16,ON,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT02_TEXT,NULL},
	{OBJ_TEXT_LHT03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,628,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT03_TEXT,NULL},
	{OBJ_TEXT_LHT04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,685,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT04_TEXT,NULL},
	{OBJ_TEXT_LHT05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,742,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT05_TEXT,NULL},
	{OBJ_TEXT_LHT06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,799,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT06_TEXT,NULL},
	{OBJ_TEXT_LHT07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,856,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT07_TEXT,NULL},
	{OBJ_TEXT_LHT08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,913,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT08_TEXT,NULL},
	{OBJ_TEXT_LHT09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,333,970,110,16,OFF,OFF,0,Font20,(wchar_t *)&OBJ_TEXT_LHT09_TEXT,NULL},
	{OBJ_TEXT_DAMPER00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,457,110,16,ON,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER00_TEXT,NULL},
	{OBJ_TEXT_DAMPER01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,514,110,16,ON,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER01_TEXT,NULL},
	{OBJ_TEXT_DAMPER02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,571,110,16,ON,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER02_TEXT,NULL},
	{OBJ_TEXT_DAMPER03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,628,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER03_TEXT,NULL},
	{OBJ_TEXT_DAMPER04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,685,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER04_TEXT,NULL},
	{OBJ_TEXT_DAMPER05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,742,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER05_TEXT,NULL},
	{OBJ_TEXT_DAMPER06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,799,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER06_TEXT,NULL},
	{OBJ_TEXT_DAMPER07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,856,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER07_TEXT,NULL},
	{OBJ_TEXT_DAMPER08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,913,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER08_TEXT,NULL},
	{OBJ_TEXT_DAMPER09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,450,970,110,16,OFF,OFF,0,Font24,(wchar_t *)&OBJ_TEXT_DAMPER09_TEXT,NULL},
	{OBJ_IMG_DAMPER00,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,430,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER01,logo_mode_natural,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,487,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER02,logo_mode_auto,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,544,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER03,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,601,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER04,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,658,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER05,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,715,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER06,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,772,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER07,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,829,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER08,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,886,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_DAMPER09,logo_mode_close,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,371,943,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_TEXT_STEAM00,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,457,104,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM00_TEXT,NULL},
	{OBJ_TEXT_STEAM01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,514,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM01_TEXT,NULL},
	{OBJ_TEXT_STEAM02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,571,104,24,ON,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM02_TEXT,NULL},
	{OBJ_TEXT_STEAM03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,628,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM03_TEXT,NULL},
	{OBJ_TEXT_STEAM04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,685,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM04_TEXT,NULL},
	{OBJ_TEXT_STEAM05,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,742,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM05_TEXT,NULL},
	{OBJ_TEXT_STEAM06,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,799,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM06_TEXT,NULL},
	{OBJ_TEXT_STEAM07,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,856,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM07_TEXT,NULL},
	{OBJ_TEXT_STEAM08,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,913,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM08_TEXT,NULL},
	{OBJ_TEXT_STEAM09,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_TEXT,OBJECT_DRAW_TYPE_CENTER,530,970,104,24,OFF,OFF,0,Font36,(wchar_t *)&OBJ_TEXT_STEAM09_TEXT,NULL},
	{OBJ_IMG_STEAM01,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,487,117,137,ON,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM02,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,544,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM03,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,601,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM04,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,658,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM05,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,715,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM06,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,772,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM07,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,829,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM08,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,886,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_IMG_STEAM09,logo_steam,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_IMG,OBJECT_DRAW_TYPE_NORMAL,510,943,117,137,OFF,OFF,0,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_TABLE01,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,154,430,3,567,ON,OFF,0xFF5a5a5a,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_TABLE02,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,261,430,3,567,ON,OFF,0xFF5a5a5a,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_TABLE03,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,368,430,3,567,ON,OFF,0xFF5a5a5a,0,(wchar_t *)&TEXT_DATA_NON,NULL},
	{OBJ_RECT_TABLE04,IMG_NONE,IMG_NONE,IMG_NONE,GRAFIC_OBJECT_TYPE_RECTANGLE,OBJECT_DRAW_TYPE_NORMAL,475,430,3,567,ON,OFF,0xFF5a5a5a,0,(wchar_t *)&TEXT_DATA_NON,NULL},
};

void L_DETAIL00_LoadLayer(layer_data_t *layer)
{
	NewLayer(layer , L_DETAIL00 , object_list , 181 , (VOID_CALLBACK)L_DETAIL00_start , (VOID_CALLBACK)L_DETAIL00_end , (VOID_CALLBACK)L_DETAIL00_always);
}
/**********auto(end)**********/

const int t_ct_img[9] = {OBJ_IMG_T_CT01 , OBJ_IMG_T_CT02 , OBJ_IMG_T_CT03 , OBJ_IMG_T_CT04 ,
		OBJ_IMG_T_CT05 , OBJ_IMG_T_CT06 , OBJ_IMG_T_CT07 , OBJ_IMG_T_CT08 , OBJ_IMG_T_CT09};
const int time1_text[9] = {OBJ_TEXT_TIME011 , OBJ_TEXT_TIME021 , OBJ_TEXT_TIME031 , OBJ_TEXT_TIME041 ,
		OBJ_TEXT_TIME051 , OBJ_TEXT_TIME061 , OBJ_TEXT_TIME071 , OBJ_TEXT_TIME081 , OBJ_TEXT_TIME091};
const int time2_text[9] = {OBJ_TEXT_TIME012 , OBJ_TEXT_TIME022 , OBJ_TEXT_TIME032 , OBJ_TEXT_TIME042 ,
		OBJ_TEXT_TIME052 , OBJ_TEXT_TIME062 , OBJ_TEXT_TIME072 , OBJ_TEXT_TIME082 , OBJ_TEXT_TIME092};
const int time3_text[9] = {OBJ_TEXT_TIME013 , OBJ_TEXT_TIME023 , OBJ_TEXT_TIME033 , OBJ_TEXT_TIME043 ,
		OBJ_TEXT_TIME053 , OBJ_TEXT_TIME063 , OBJ_TEXT_TIME073 , OBJ_TEXT_TIME083 , OBJ_TEXT_TIME093};
const int time4_text[9] = {OBJ_TEXT_TIME014 , OBJ_TEXT_TIME024 , OBJ_TEXT_TIME034 , OBJ_TEXT_TIME044 ,
		OBJ_TEXT_TIME054 , OBJ_TEXT_TIME064 , OBJ_TEXT_TIME074 , OBJ_TEXT_TIME084 , OBJ_TEXT_TIME094};
const int ct_text[9] = {OBJ_TEXT_CT01 , OBJ_TEXT_CT02 , OBJ_TEXT_CT03 , OBJ_TEXT_CT04 ,
		OBJ_TEXT_CT05 , OBJ_TEXT_CT06 , OBJ_TEXT_CT07 , OBJ_TEXT_CT08 , OBJ_TEXT_CT09};
const int steam_img[9] = {OBJ_IMG_STEAM01 , OBJ_IMG_STEAM02 , OBJ_IMG_STEAM03 , OBJ_IMG_STEAM04 ,
		OBJ_IMG_STEAM05 , OBJ_IMG_STEAM06 , OBJ_IMG_STEAM07 , OBJ_IMG_STEAM08 , OBJ_IMG_STEAM09};
const int steam_text[9] = {OBJ_TEXT_STEAM01 , OBJ_TEXT_STEAM02 , OBJ_TEXT_STEAM03 , OBJ_TEXT_STEAM04 ,
		OBJ_TEXT_STEAM05 , OBJ_TEXT_STEAM06 , OBJ_TEXT_STEAM07 , OBJ_TEXT_STEAM08 , OBJ_TEXT_STEAM09};
const int uhm_img[10] = {OBJ_IMG_UHM00 , OBJ_IMG_UHM01 , OBJ_IMG_UHM02 , OBJ_IMG_UHM03 , OBJ_IMG_UHM04 ,
		OBJ_IMG_UHM05 , OBJ_IMG_UHM06 , OBJ_IMG_UHM07 , OBJ_IMG_UHM08 , OBJ_IMG_UHM09};
const int uht_text[10] = {OBJ_TEXT_UHT00 , OBJ_TEXT_UHT01 , OBJ_TEXT_UHT02 , OBJ_TEXT_UHT03 , OBJ_TEXT_UHT04 ,
		OBJ_TEXT_UHT05 , OBJ_TEXT_UHT06 , OBJ_TEXT_UHT07 , OBJ_TEXT_UHT08 , OBJ_TEXT_UHT09};
const int lhm_img[10] = {OBJ_IMG_LHM00 , OBJ_IMG_LHM01 , OBJ_IMG_LHM02 , OBJ_IMG_LHM03 , OBJ_IMG_LHM04 ,
		OBJ_IMG_LHM05 , OBJ_IMG_LHM06 , OBJ_IMG_LHM07 , OBJ_IMG_LHM08 , OBJ_IMG_LHM09};
const int lht_text[10] = {OBJ_TEXT_LHT00 , OBJ_TEXT_LHT01 , OBJ_TEXT_LHT02 , OBJ_TEXT_LHT03 , OBJ_TEXT_LHT04 ,
		OBJ_TEXT_LHT05 , OBJ_TEXT_LHT06 , OBJ_TEXT_LHT07 , OBJ_TEXT_LHT08 , OBJ_TEXT_LHT09};
const int damper_img[10] = {OBJ_IMG_DAMPER00 , OBJ_IMG_DAMPER01 , OBJ_IMG_DAMPER02 , OBJ_IMG_DAMPER03 , OBJ_IMG_DAMPER04 ,
		OBJ_IMG_DAMPER05 , OBJ_IMG_DAMPER06 , OBJ_IMG_DAMPER07 , OBJ_IMG_DAMPER08 , OBJ_IMG_DAMPER09};
const int damper_text[10] = {OBJ_TEXT_DAMPER00 , OBJ_TEXT_DAMPER01 , OBJ_TEXT_DAMPER02 , OBJ_TEXT_DAMPER03 , OBJ_TEXT_DAMPER04 ,
		OBJ_TEXT_DAMPER05 , OBJ_TEXT_DAMPER06 , OBJ_TEXT_DAMPER07 , OBJ_TEXT_DAMPER08 , OBJ_TEXT_DAMPER09};
const int on_color_rect[10] = {OBJ_RECT_PROCESS00 , OBJ_RECT_PROCESS01 , OBJ_RECT_PROCESS02 , OBJ_RECT_PROCESS03 , OBJ_RECT_PROCESS04 ,
		OBJ_RECT_PROCESS05 , OBJ_RECT_PROCESS06 , OBJ_RECT_PROCESS07 , OBJ_RECT_PROCESS08 , OBJ_RECT_PROCESS09};

/*
 *		レイヤーの表示開始時の処理
 */
static void L_DETAIL00_start(void)
{
	
}

/*
 *		レイヤーの表示終了時の処理
 */
static void L_DETAIL00_end(void)
{
	
}

/*
 *		レイヤーの定期処理
 */
static void L_DETAIL00_always(void)
{
	obj_SetString_Number(OBJ_TEXT_TITLE00, cl.code_no_select, 12);
	obj_SetString(OBJ_TEXT_TITLE02, a.code_name[cl.code_no_select - 2]);

	switch (a.process_change[cl.code_no_select - 2]) {
	case S_AUTO:
		obj_set_img(OBJ_IMG_AMSELECT00, amselect_a_off);
		obj_set_touch_img(OBJ_IMG_AMSELECT00, amselect_a_on);
		break;
	case S_MANUAL:
		obj_set_img(OBJ_IMG_AMSELECT00, amselect_m_off);
		obj_set_touch_img(OBJ_IMG_AMSELECT00, amselect_m_on);
		break;
	}

	switch (a.warmup_buzzer[cl.code_no_select - 2]) {
	case STS_TRUE:
		obj_set_img(OBJ_IMG_NOTICESELECT00, noticeselect_b_off);
		obj_set_touch_img(OBJ_IMG_NOTICESELECT00, noticeselect_b_on);
		break;
	case STS_NONE:
		obj_set_img(OBJ_IMG_NOTICESELECT00, noticeselect_a_off);
		obj_set_touch_img(OBJ_IMG_NOTICESELECT00, noticeselect_a_on);
		break;
	}

	for(int i = 0; i <= 9; i++) {

		if(a.uh_temp[cl.code_no_select - 2][i] > 99) {
			obj_SetString_Number(uht_text[i],
					a.uh_temp[cl.code_no_select - 2][i], 3);
		}
		else if(a.uh_temp[cl.code_no_select - 2][i] > 9) {
			obj_SetString_Number(uht_text[i],
					a.uh_temp[cl.code_no_select - 2][i], 2);
		}
		else{
			obj_SetString_Number(uht_text[i],
					a.uh_temp[cl.code_no_select - 2][i], 1);
		}

		if(a.lh_temp[cl.code_no_select - 2][i] > 99) {
			obj_SetString_Number(lht_text[i],
					a.lh_temp[cl.code_no_select - 2][i], 3);
		}
		else if(a.lh_temp[cl.code_no_select - 2][0] > 9){
			obj_SetString_Number(lht_text[i],
					a.lh_temp[cl.code_no_select - 2][i], 2);
		}
		else{
			obj_SetString_Number(lht_text[i],
					a.lh_temp[cl.code_no_select - 2][i], 1);
		}

		switch(a.uh_mode[cl.code_no_select - 2][i]) {
		case HIGH:
			obj_set_img(uhm_img[i], logo_mode_high);
			break;
		case MEDIUM:
			obj_set_img(uhm_img[i], logo_mode_medium);
			break;
		case LOW:
			obj_set_img(uhm_img[i], logo_mode_low);
			break;
		}

		switch(a.lh_mode[cl.code_no_select - 2][i]) {
		case HIGH:
			obj_set_img(lhm_img[i], logo_mode_high);
			break;
		case MEDIUM:
			obj_set_img(lhm_img[i], logo_mode_medium);
			break;
		case LOW:
			obj_set_img(lhm_img[i], logo_mode_low);
			break;
		}

		switch(a.core_temp_sts[cl.code_no_select - 2][i - 1]) {
		case STS_TRUE:
			obj_set_img(t_ct_img[i - 1], logo_mode_coretemp);
			obj_hide(time1_text[i - 1]);
			obj_hide(time2_text[i - 1]);
			obj_hide(time3_text[i - 1]);
			obj_hide(time4_text[i - 1]);
			obj_show(ct_text[i - 1]);

			//芯温度


			break;
		case STS_NONE:
			obj_set_img(t_ct_img[i - 1], logo_mode_time);
			obj_show(time1_text[i - 1]);
			obj_show(time2_text[i - 1]);
			obj_show(time3_text[i - 1]);
			obj_show(time4_text[i - 1]);
			obj_hide(ct_text[i - 1]);
			obj_SetString_Number(time1_text[i - 1],
					a.time_minute[cl.code_no_select - 2][i - 1], 12);
			obj_SetString_Number(time3_text[i - 1],
					a.time_second[cl.code_no_select - 2][i - 1], 12);
			break;
		}

		switch(a.damper_sts[cl.code_no_select - 2][i]) {
		case D_CLOSE:
			obj_SetString(damper_text[i], L"閉");
			obj_set_img(damper_img[i], logo_mode_close);
			break;
		case D_NATURAL:
			obj_SetString(damper_text[i], L"自然");
			obj_set_img(damper_img[i], logo_mode_natural);
			break;
		case D_AUTO:
			obj_SetString(damper_text[i], L"強制");
			obj_set_img(damper_img[i], logo_mode_auto);
			break;
		}

		if(i <= a.process_max[cl.code_no_select - 2]){
			if(i == 0){
				obj_show(uhm_img[i]);
				obj_show(lhm_img[i]);
				obj_show(uht_text[i]);
				obj_show(lht_text[i]);
				obj_show(damper_img[i]);
				obj_show(damper_text[i]);
			}
			else{
				obj_show(uhm_img[i]);
				obj_show(lhm_img[i]);
				obj_show(uht_text[i]);
				obj_show(lht_text[i]);
				obj_show(damper_img[i]);
				obj_show(damper_text[i]);
				obj_show(t_ct_img[i - 1]);
				obj_show(steam_img[i - 1]);
				obj_show(steam_text[i - 1]);
			}
		}
		else{
			if(i == 0){
				obj_hide(uhm_img[i]);
				obj_hide(lhm_img[i]);
				obj_hide(uht_text[i]);
				obj_hide(lht_text[i]);
				obj_hide(damper_img[i]);
				obj_hide(damper_text[i]);
			}
			else{
				obj_hide(uhm_img[i]);
				obj_hide(lhm_img[i]);
				obj_hide(uht_text[i]);
				obj_hide(lht_text[i]);
				obj_hide(damper_img[i]);
				obj_hide(damper_text[i]);
				obj_hide(t_ct_img[i - 1]);
				obj_hide(time1_text[i - 1]);
				obj_hide(time2_text[i - 1]);
				obj_hide(time3_text[i - 1]);
				obj_hide(time4_text[i - 1]);
				obj_hide(ct_text[i - 1]);
				obj_hide(steam_img[i - 1]);
				obj_hide(steam_text[i - 1]);
			}
		}
		if(d.rect_on_color[i] == STS_TRUE){
			obj_set_color(on_color_rect[i] , 0xFF5A5A5A);
		}
		else{
			obj_set_color(on_color_rect[i] , 0xFF000000);
		}
	}

	switch(d.m_select){
	case D_MODE_NONE:
		obj_set_img(OBJ_IMG_SELECT00, cd_deleate_a_off);
		obj_set_img(OBJ_IMG_SELECT01, cd_edit_a_off);
		obj_set_touch_img(OBJ_IMG_SELECT00, cd_deleate_a_on);
		obj_set_touch_img(OBJ_IMG_SELECT01, cd_edit_a_on);
		for( int i = 0; i < 10; i++){
			obj_set_touch(on_color_rect[i], false);
		}
		break;
	case D_MODE_DELEATE:
		obj_set_img(OBJ_IMG_SELECT00, cd_deleate_b_off);
		obj_set_img(OBJ_IMG_SELECT01, cd_edit_a_off);
		obj_set_touch_img(OBJ_IMG_SELECT00, cd_deleate_b_on);
		obj_set_touch_img(OBJ_IMG_SELECT01, cd_edit_a_on);
		obj_set_touch(on_color_rect[0], false);
		for( int i = 1; i < 10; i++){
			obj_set_touch(on_color_rect[i], true);
		}
		break;
	case D_MODE_EDIT:
		obj_set_img(OBJ_IMG_SELECT00, cd_deleate_a_off);
		obj_set_img(OBJ_IMG_SELECT01, cd_edit_b_off);
		obj_set_touch_img(OBJ_IMG_SELECT00, cd_deleate_a_on);
		obj_set_touch_img(OBJ_IMG_SELECT01, cd_edit_b_on);
		for( int i = 0; i < 10; i++){
			obj_set_touch(on_color_rect[i], true);
		}
		break;
	}
}
void Process_Mode_Migarate(void) {
	switch(d.m_select){
	case D_MODE_DELEATE:
		if(d.process_no_select != 0) {
			for(int i = d.process_no_select;
					i <= a.process_max[cl.code_no_select - 2] - 1; i++){
				a.time_minute[cl.code_no_select - 2][i - 1] =
						a.time_minute[cl.code_no_select - 2][i];
				a.time_second[cl.code_no_select - 2][i - 1] =
						a.time_second[cl.code_no_select - 2][i];
				a.uh_temp[cl.code_no_select - 2][i] =
						a.uh_temp[cl.code_no_select - 2][i + 1];
				a.lh_temp[cl.code_no_select - 2][i] =
						a.lh_temp[cl.code_no_select - 2][i + 1];
				a.core_temp_integer[cl.code_no_select - 2][i - 1] =
						a.core_temp_integer[cl.code_no_select - 2][i];
				a.core_temp_decimal[cl.code_no_select - 2][i - 1] =
						a.core_temp_decimal[cl.code_no_select - 2][i];
				a.uh_mode[cl.code_no_select - 2][i] =
						a.uh_mode[cl.code_no_select - 2][i + 1];
				a.lh_mode[cl.code_no_select - 2][i] =
						a.lh_mode[cl.code_no_select - 2][i + 1];
				a.damper_sts[cl.code_no_select - 2][i] =
						a.damper_sts[cl.code_no_select - 2][i + 1];
				a.core_temp_sts[cl.code_no_select - 2][i - 1] =
						a.core_temp_sts[cl.code_no_select - 2][i];
				a.steam_sts[cl.code_no_select - 2][i - 1] =
						a.steam_sts[cl.code_no_select - 2][i];
			}

			for(int i = 9;
					i > a.process_max[cl.code_no_select - 2] - 1;i--){
				a.time_minute[cl.code_no_select - 2][i - 1] = 0;
				a.time_second[cl.code_no_select - 2][i - 1] = 0;
				a.uh_temp[cl.code_no_select - 2][i] = 0;
				a.lh_temp[cl.code_no_select - 2][i] = 0;
				a.core_temp_integer[cl.code_no_select - 2][i - 1] = 0;
				a.core_temp_decimal[cl.code_no_select - 2][i - 1] = 0;
				a.uh_mode[cl.code_no_select - 2][i] = HIGH;
				a.lh_mode[cl.code_no_select - 2][i] = HIGH;
				a.damper_sts[cl.code_no_select - 2][i] = D_CLOSE;
				a.core_temp_sts[cl.code_no_select - 2][i - 1] = STS_NONE;
				a.steam_sts[cl.code_no_select - 2][i - 1] = STS_NONE;
			}
			a.process_max[cl.code_no_select] = a.process_max[cl.code_no_select] - 1;
		}
		break;
	case D_MODE_EDIT:
		/*各工程設定画面ができ次第、記載*/
		break;
	}
}

/**********touch_source**********/

/*
 *          OBJ_IMG_SELECT00をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_IMG_SELECT00_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		switch(d.m_select){
		case D_MODE_DELEATE:
			d.m_select = D_MODE_NONE;
			break;
		default:
			d.m_select = D_MODE_DELEATE;
			break;
		}
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_IMG_SELECT01をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_IMG_SELECT01_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		switch(d.m_select){
		case D_MODE_EDIT:
			d.m_select = D_MODE_NONE;
			break;
		default:
			d.m_select = D_MODE_EDIT;
			break;
		}
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_IMG_SELECT02をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_IMG_SELECT02_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		change_mode(MODE_CODELIST);
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_IMG_AMSELECT00をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_IMG_AMSELECT00_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		switch(a.process_change[cl.code_no_select - 2]){
		case S_MANUAL:
			a.process_change[cl.code_no_select - 2] = S_AUTO;
			break;
		default:
			a.process_change[cl.code_no_select - 2] = S_MANUAL;
			break;
		}
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_IMG_NOTICESELECT00をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_IMG_NOTICESELECT00_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		switch(a.warmup_buzzer[cl.code_no_select - 2]){
		case STS_TRUE:
			a.warmup_buzzer[cl.code_no_select - 2] = STS_NONE;
			break;
		default:
			a.warmup_buzzer[cl.code_no_select - 2] = STS_TRUE;
			break;
		}
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS00をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS00_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 0;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS01をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS01_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 1;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS02をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS02_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 2;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS03をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS03_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 3;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS04をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS04_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 4;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS05をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS05_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 5;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS06をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS06_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 6;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS07をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS07_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 7;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS08をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS08_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 8;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}

/*
 *          OBJ_RECT_PROCESS09をタッチした場合
 *          (関数宣言を変更しないで下さい)
 */
static void OBJ_RECT_PROCESS09_touch(int obj_id , int touch_type)
{
	switch(touch_type){
	case TOUCH_ON:				// タッチした瞬間
		break;
	case TOUCH_LONG:			// タッチし続けて1秒
		break;
	case TOUCH_OFF:				// 放した瞬間
		d.process_no_select = 9;
		Process_Mode_Migarate();
		break;
	case TOUCH_SHORT_OFF:		// 押してすぐ放した
		break;
	case TOUCH_REPEAT:			// タッチ後1秒の後連続
		break;
	}
}
