/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  DAIW1923A                              */
/*      FILE         :  DAIW1923A.c                            */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/
#include <typedefine.h>
#include <iodefine.h>
#include "hw_setting.h"





void initCPUClock(void)
{
	
	
	
	
	
	
	
	
	
}
