/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  DAIW1923A                              */
/*      FILE         :  DAIW1923A.c                            */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/
#include <iodefine.h>
#include "hw_setting.h"
#include "os/intc.h"
#include "stdinx.h"
#include "io.h"

#define OSPL_CPG_STBCR5_MSTP51               (0x02u)
#define OSPL_CPG_STBCR5_MSTP33               (0x08u)




void OsTimerInit(void)
{
	CPG.STBCR5 &= ~(OSPL_CPG_STBCR_MSTP1); /* enable OSTM0 clock */


	OSTM0.OSTMnCMP = 2999;						// 0.1msec毎
	OSTM0.OSTMnTS = 1;
	OSTM0.OSTMnCTL = 1;
	IRQ_SetPriority(OSTMI0TINT_IRQn , 2);
	IRQ_Enable(OSTMI0TINT_IRQn);
	
	
	
	
	
	
}

void mtu2Init(void)
{
	CPG.STBCR3 &= ~(OSPL_CPG_STBCR5_MSTP33); /* enable AD clock */
	// 液晶のバックライトの明るさ制御用PWMの設定
	MTU2.TCR_1 = 0x20;			// カウンタクロックの設定,カウンタクリア要件の設定
	MTU2.TIOR_1 = 0x16;			// 出力波形の設定
	MTU2.TIER_1 = 0x00;			//
	MTU2.TMDR_1 = 0x02;
	MTU2.TGRB_1 = 1;
	MTU2.TGRA_1 = 1500;
	MTU2.TSTR |= 0x02;
	// ポート設定
    // P8_13=TxD0(Alternative Mode 5,Output:PFCAE1,PFCE0,PFC0)
    GPIO.PIBC8  &=~(uint32_t)GPIO_BIT_N8;				// ポート入力バッファ制御レジスタ 0：禁止 1:許可
    GPIO.PBDC8  &=~(uint32_t)GPIO_BIT_N8;				// ポート双方向モード 0：禁止 1:許可
    GPIO.PM8    &=~(uint32_t)GPIO_BIT_N8;				// ポート方向レジスタ 0：出力モード 1:入力モード
    GPIO.PMC8   &=~(uint32_t)GPIO_BIT_N8;				// ポートモードレジスタ 0:ポートモード 1:兼用モード
    GPIO.PIPC8  &=~(uint32_t)GPIO_BIT_N8;				// ポートIP制御レジスタ 0：入出力はPMによって制御 1:入出力は兼用機能によって制御

    GPIO.PBDC8  &=~(uint32_t)GPIO_BIT_N8;				// ポート双方向モード 0：禁止 1:許可
    GPIO.PFCAE8 |= (uint32_t)GPIO_BIT_N8;				// ポート機能制御追加拡張レジスタ
    GPIO.PFCE8  &=~(uint32_t)GPIO_BIT_N8;				// ポート機能制御拡張レジスタ
    GPIO.PFC8   &=~(uint32_t)GPIO_BIT_N8;				// ポート機能制御レジスタ

    GPIO.PIPC8  |= (uint32_t)GPIO_BIT_N8;				// ポートIP制御レジスタ 0：入出力はPMによって制御 1:入出力は兼用機能によって制御
    GPIO.PMC8   |= (uint32_t)GPIO_BIT_N8;				// ポートモードレジスタ 0:ポートモード 1:兼用モード
    BACK_LIGHT_PWM(0);
}


void BACK_LIGHT_PWM(int par)
{
	if(par == 0){
	    GPIO.PMC8   &=~(uint32_t)GPIO_BIT_N8;				// ポートモードレジスタ 0:ポートモード 1:兼用モード
		O_BACKLIGHT(OFF);										// バックライトの初期設定
	}else if(par == 100){
	    GPIO.PMC8   &=~(uint32_t)GPIO_BIT_N8;				// ポートモードレジスタ 0:ポートモード 1:兼用モード
		O_BACKLIGHT(ON);										// バックライトの初期設定
	}else{
	    GPIO.PMC8   |= (uint32_t)GPIO_BIT_N8;				// ポートモードレジスタ 0:ポートモード 1:兼用モード
		int w = par * MTU2.TGRA_1 / 100;
		if(w >= MTU2.TGRA_1){
			w = MTU2.TGRA_1 - 1;
		}
		if(w == 0){
			w = 1;
		}
		MTU2.TGRB_1 = w;

	}
}







void initTimer(void)
{
	OsTimerInit();
	mtu2Init();
	
	
	
	
	
	
	
	
	
}
