/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  DAIW1923A                              */
/*      FILE         :  DAIW1923A.c                            */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/
//#include <typedefine.h>
#include <iodefine.h>
#include "hw_setting.h"
#include "graphics_ctrl.h"
#include "ad_ctrl.h"
#include "touch_ctrl.h"
#include "usb_memory_delegate.h"
#include "common.h"


extern int	usb_main(void);
extern int	Main_Task(void);


void OsIdol(void)
{
    while(1) {
    	// アイドルスレッド動作
    }

}





void io_setting(void)
{
    SCIF_PortSetting(SCIF_CH_NUM_1);
    SCIF_PortSetting(SCIF_CH_NUM_2);
    SCIF_PortSetting(SCIF_CH_NUM_3);
    SCIF_PortSetting(SCIF_CH_NUM_4);
    SCIF_PortSetting(SCIF_CH_NUM_5);

    ADC_PortSetting();
    ad_Init();
    IRQ_init();
	initTimer();
	enable_int();
	initIO();
	__enable_fault_irq();



}

int main(void)
{
	io_setting();
	initOS();
	CreateThread(Graphics_Task , 8192);
	CreateThread(Main_Task , 8192);
	CreateThread(touch_ctrl_task , 4096);
	CreateThread(usb_main , 8192);
	CreateThread(Buzzer_Task , 4096);
	CreateThread(Debug_Task , 4096);


	OsIdol();
	return 0;
}


uint8_t wd_flag ;
#define WD_PATT 0xA5
#define WD_CLEAR 0x5A


/* タイマー割り込み処理
 *  1msec毎
 */
void common_exe_timer_handler(void)
{
	static int count = 0;
	static int wd_out = 0;


	/* 10msec処理 */
	count++;
	if(count >= 10){
		count = 0;
		if(wd_flag == WD_PATT)
		{
//			if(info.soft_reset != 0xAABBCCDD){
				wd_flag = WD_CLEAR;
				O_WD(wd_out );
				if(wd_out == 0){
					wd_out = 1;
				}else{
					wd_out = 0;
				}
//			}
		}
	}
}


/*******************************************************************************
 *	wd_flag_set
 *	機能	ｳｫｯﾁﾄﾞｯｸﾞﾌﾗｸﾞをｾｯﾄする
 *	引数	なし
 *	返り値	なし
 ******************************************************************************/
void wd_flag_set(void)
{
	wd_flag = WD_PATT;
}


